"""
Evidence Item Schema
Pydantic model for normalizing collected market research data.
"""
from typing import Optional, List, Dict, Any
from datetime import datetime
from pydantic import BaseModel, Field, field_validator


class EvidenceItem(BaseModel):
    """
    Normalized schema for evidence items collected from various sources.
    Includes source information, engagement metrics, and extracted content.
    """
    
    # Unique identifier
    id: str = Field(description="Unique identifier for the evidence item")
    
    # Source information
    source: str = Field(description="Source platform (reddit, youtube, tiktok, app_store, media)")
    source_url: str = Field(description="URL or reference to the source")
    source_type: str = Field(description="Type of source (post, comment, video, review, article)")
    
    # Content
    title: Optional[str] = Field(default=None, description="Title of the content")
    content: str = Field(description="Main text content or description")
    author: Optional[str] = Field(default=None, description="Author or username")
    
    # Timestamps
    collected_at: datetime = Field(default_factory=datetime.now, description="When data was collected")
    published_at: Optional[datetime] = Field(default=None, description="When content was published")
    
    # Engagement metrics
    engagement_metrics: Dict[str, Any] = Field(
        default_factory=dict,
        description="Metrics like upvotes, views, likes, comments count"
    )
    
    # Tags and classification (populated by Tagger Agent)
    segment: Optional[str] = Field(default=None, description="User segment classification")
    moment: Optional[str] = Field(default=None, description="User moment or context")
    job: Optional[str] = Field(default=None, description="Job to be done")
    themes: List[str] = Field(default_factory=list, description="Identified themes")
    sentiment: Optional[str] = Field(default=None, description="Sentiment: positive, negative, neutral")
    
    # Additional metadata
    metadata: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional platform-specific metadata"
    )
    
    @field_validator('sentiment')
    @classmethod
    def validate_sentiment(cls, v):
        """Validate sentiment values"""
        if v is not None and v not in ['positive', 'negative', 'neutral', 'mixed']:
            raise ValueError(f"Invalid sentiment: {v}. Must be positive, negative, neutral, or mixed")
        return v
    
    @field_validator('source')
    @classmethod
    def validate_source(cls, v):
        """Validate source platform"""
        valid_sources = ['reddit', 'youtube', 'tiktok', 'app_store', 'media', 'twitter', 'other']
        if v not in valid_sources:
            raise ValueError(f"Invalid source: {v}. Must be one of {valid_sources}")
        return v
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "reddit_post_12345",
                "source": "reddit",
                "source_url": "https://reddit.com/r/soccer/comments/12345",
                "source_type": "post",
                "title": "Best soccer cleats for youth players",
                "content": "Looking for recommendations on soccer cleats for my 12-year-old...",
                "author": "soccer_parent_2024",
                "published_at": "2024-01-15T10:30:00",
                "engagement_metrics": {
                    "upvotes": 45,
                    "comments": 23
                },
                "segment": "parents",
                "moment": "purchasing_decision",
                "job": "find_quality_equipment",
                "themes": ["youth_soccer", "equipment", "recommendations"],
                "sentiment": "neutral"
            }
        }


class ResearchPlan(BaseModel):
    """
    Research plan schema generated by Planner Agent.
    """
    
    research_topic: str = Field(description="Main research topic or question")
    target_segments: List[str] = Field(description="Target user segments to research")
    
    # Source configuration
    sources: Dict[str, Dict[str, Any]] = Field(
        description="Configuration for each data source"
    )
    
    # Collection quotas
    quotas: Dict[str, int] = Field(
        description="Target number of items to collect per source"
    )
    
    # Stop conditions
    stop_conditions: Dict[str, Any] = Field(
        default_factory=dict,
        description="Conditions for stopping collection (max_items, time_limit, etc.)"
    )
    
    # Search keywords and filters
    keywords: List[str] = Field(default_factory=list, description="Keywords for search")
    filters: Dict[str, Any] = Field(default_factory=dict, description="Additional filters")
    
    class Config:
        json_schema_extra = {
            "example": {
                "research_topic": "Youth soccer equipment preferences",
                "target_segments": ["parents", "youth_players", "coaches"],
                "sources": {
                    "reddit": {
                        "subreddits": ["soccer", "bootroom", "youthsoccer"],
                        "time_filter": "month"
                    },
                    "youtube": {
                        "search_terms": ["youth soccer cleats", "soccer equipment review"],
                        "max_results": 50
                    }
                },
                "quotas": {
                    "reddit": 100,
                    "youtube": 50,
                    "app_store": 100
                },
                "stop_conditions": {
                    "max_total_items": 500,
                    "time_limit_hours": 24
                },
                "keywords": ["soccer", "cleats", "equipment", "youth", "training"]
            }
        }
